version: 2
build:
  os: "ubuntu-22.04"
  tools:
    python: "mambaforge-22.9"
sphinx:
  configuration: docs/conf.py
formats: all
conda:
  environment: conda/bicycleparameters-dev.yml
python:
  install:
    - method: setuptools
      path: .
